### ISSUE TITLE
REJECT-CLAIM-NOTIFICATION tasks are failing on test

### ISSUE THREAD

**Issue by stevenalexander** [ministryofjustice/apvs-asynchronous-worker#138]
env: test

Steps:
- Submit and reject a claim

Expected:
- receive rejection notification

Actual:
- no notification

Seeing failed tasks in Test due to error calling Notify.

Kibana log:
```
{"@timestamp":"2017-02-01T15:20:36.519Z","message":"","tags":["bunyan"],"source":"test-wrk-1/node /usr/src/app/apvs-asynchronous-worker/start.js","level":"error","name":"asynchronous-worker","hostname":"test-wrk-1","pid":65410,"error":{"message":"400 - {\"message\":{\"template\":[\"Missing personalisation: first_name, requestInfoUrl\"]},\"result\":\"error\"}","name":"StatusCodeError","stack":"StatusCodeError: 400 - {\"message\":{\"template\":[\"Missing personalisation: first_name, requestInfoUrl\"]},\"result\":\"error\"}\n    at new StatusCodeError (/usr/src/app/apvs-asynchronous-worker/node_modules/request-promise-core/lib/errors.js:32:15)\n    at Request.plumbing.callback (/usr/src/app/apvs-asynchronous-worker/node_modules/request-promise-core/lib/plumbing.js:104:33)\n    at Request.RP$callback [as _callback] (/usr/src/app/apvs-asynchronous-worker/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at Request.self.callback (/usr/src/app/apvs-asynchronous-worker/node_modules/request/request.js:186:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/usr/src/app/apvs-asynchronous-worker/node_modules/request/request.js:1081:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/usr/src/app/apvs-asynchronous-worker/node_modules/request/request.js:1001:12)\n    at IncomingMessage.g (events.js:291:16)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)"}}
```

**Comment by gdouglas1** [comment]
The reason for this issue is changes that are currently being made to most of the email templates to include first name and the request info URL (see https://github.com/ministryofjustice/apvs-asynchronous-worker/pull/135).

**Comment by stevenalexander** [comment]
Issue is caused by trying to use data module `get-first-name-by-claimId` with `reference`, so result is empty.

`apvs-asynchronous-worker/app/services/workers/send-rejected-claim-notification.js` ln8

**Comment by msjhall138** [comment]
Verified
